#!/bin/bash                             
#PBS -l nodes=1:ppn=4,mem=15gb,walltime=24:00:00
#PBS -m abe
#PBS -M onson001@umn.edu

ssh galaxy-ng

sudo su - gxtest

INSTALL_PATH=/home/galaxy/gxtest/tmp/cnv
MYSQL_LOAD_WAIT=120

cd $INSTALL_PATH

source /website/galaxy-ng.msi.umn.edu/NEXTGEN/tool_dependencies/R/3.1.2/iuc/package_r_3_1_2/7cb487a32bde/env.sh 


wget https://s3.msi.umn.edu/CNVMySQL/mysql-5.6.24-linux-glibc2.5-x86_64.tar.gz

tar xzvf mysql-5.6.24-linux-glibc2.5-x86_64.tar.gz

# SET UP THE mysql DATA DIRECTORY INSTALL
mkdir -p mysql/data

cd $INSTALL_PATH/mysql-5.6.24-linux-glibc2.5-x86_64

./scripts/mysql_install_db -datadir=$INSTALL_PATH/mysql/data

cd $INSTALL_PATH

# MAKE ENVIRONMENT AWARE OF PATH TO MYSQL EXECUTABLES
export PATH=$INSTALL_PATH/mysql-5.6.24-linux-glibc2.5-x86_64/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$INSTALL_PATH/mysql-5.6.24-linux-glibc2.5-x86_64/lib


# START MYSQL 
mysqld --innodb_buffer_pool_size=4G --basedir=$INSTALL_PATH/mysql --datadir=$INSTALL_PATH/mysql/data --log-error=$INSTALL_PATH/mysql/data/mysql.err --pid-file=$INSTALL_PATH/mysql/mysql.pid --socket=$INSTALL_PATH/mysql/thesock --port=3306 --lc-messages-dir=$INSTALL_PATH/mysql-5.6.24-linux-glibc2.5-x86_64/share/english &

# CHECK TO MAKE SURE MYSQL HAS STARTED BEFORE PROCEEDING)
#
# I TRIED TO IMPLEMENT A ROBUST SOLUTION BUT IT IS STILL BUGGY. AS A SHORT TERM FIX, I WILL USE THE SLEEP 
# COMMAND. NOTE: THIS WILL ONLY WORK IF MySQL LOAD WITHIN THE TIME LIMIT SET BY SLEEP
#
# echo "start MySQL"
# UP=$(pgrep mysql | wc -l);
# while [ "$UP" -ne 1 ]; do
#     UP=$(pgrep mysql | wc -l);
# done
# echo "MySQL successfully started"
sleep $MYSQL_LOAD_WAIT

# CREATE DATABASE
mysql --socket=$INSTALL_PATH/mysql/thesock -u root -e "CREATE DATABASE cnv;"

# LOAD CNV TABLES
wget https://s3.msi.umn.edu/CNVMySQL/mysql_tables.tar.gz

tar xzvf mysql_tables.tar.gz

mysql --socket=$INSTALL_PATH/mysql/thesock -u root cnv < tso_exon_60bp_segments_main_data.sql
mysql --socket=$INSTALL_PATH/mysql/thesock -u root cnv < tso_reference_exon.sql
mysql --socket=$INSTALL_PATH/mysql/thesock -u root cnv < tso_exon_contig_pileup.sql
mysql --socket=$INSTALL_PATH/mysql/thesock -u root cnv < tso_exon_60bp_segments_pileup.sql
mysql --socket=$INSTALL_PATH/mysql/thesock -u root cnv < tso_exon_60bp_segments_window_data.sql
mysql --socket=$INSTALL_PATH/mysql/thesock -u root cnv < tso_windows_padded_pileup.sql
mysql --socket=$INSTALL_PATH/mysql/thesock -u root cnv < tso_data.sql
mysql --socket=$INSTALL_PATH/mysql/thesock -u root cnv < training_data.sql
mysql --socket=$INSTALL_PATH/mysql/thesock -u root cnv < tso_reference.sql

wget http://cran.r-project.org/src/contrib/MASS_7.3-40.tar.gz
Rscript -e "install.packages(c('MASS_7.3-40.tar.gz'),lib='$INSTALL_PATH', repos=NULL, dependencies=FALSE)"

wget http://cran.r-project.org/src/contrib/calibrate_1.7.2.tar.gz
Rscript -e "install.packages(c('calibrate_1.7.2.tar.gz'),lib='$INSTALL_PATH', repos=NULL, dependencies=FALSE)"

wget http://cran.r-project.org/src/contrib/getopt_1.20.0.tar.gz
Rscript -e "install.packages(c('getopt_1.20.0.tar.gz'),lib='$INSTALL_PATH', repos=NULL, dependencies=FALSE)"

wget http://cran.r-project.org/src/contrib/optparse_1.3.0.tar.gz
Rscript -e "install.packages(c('optparse_1.3.0.tar.gz'),lib='$INSTALL_PATH', repos=NULL, dependencies=FALSE)"

wget http://cran.r-project.org/src/contrib/plotrix_3.5-11.tar.gz
Rscript -e "install.packages(c('plotrix_3.5-11.tar.gz'),lib='$INSTALL_PATH', repos=NULL, dependencies=FALSE)"

wget http://cran.r-project.org/src/contrib/DBI_0.3.1.tar.gz
Rscript -e "install.packages(c('DBI_0.3.1.tar.gz'),lib='$INSTALL_PATH', repos=NULL, dependencies=FALSE)"

wget http://cran.r-project.org/src/contrib/RMySQL_0.10.3.tar.gz
Rscript -e "install.packages(c('RMySQL_0.10.3.tar.gz'),lib='$INSTALL_PATH', repos=NULL, dependencies=FALSE)"

wget http://cran.r-project.org/src/contrib/zoo_1.7-12.tar.gz
Rscript -e "install.packages(c('zoo_1.7-12.tar.gz'),lib='$INSTALL_PATH', repos=NULL, dependencies=FALSE)"

wget https://s3.msi.umn.edu/CNVMySQL/CopyNumberDeletion.R
wget https://s3.msi.umn.edu/CNVMySQL/cnv_test_data.tar.gz

tar xzvf cnv_test_data.tar.gz

db_h="localhost"
db_u="root"
db_p="NULL"
db_d="cnv"
db_s="$INSTALL_PATH/mysql/thesock"

c_sample_name="07_2151";
c_pileup="test_cnv_07_2151_tso_pileup.txt"
c_bwa="test_cnv_07_2151_tso_bwa_pileup.txt"
c_bowtie="test_cnv_07_2151_tso_bowtie_pileup.txt"
sample_name="11_05910";
s_pileup="test_cnv_11_05910_tso_pileup.txt"
s_bwa="test_cnv_11_05910_tso_bwa_pileup.txt"
s_bowtie="test_cnv_11_05910_tso_bowtie_pileup.txt"
platform="TruSightOne";
ordered_genes="ordered_genes.txt"

wget https://s3.msi.umn.edu/CNVMySQL/runCNDtest.R

Rscript runCNDtest.R  --c_name $c_sample_name --c_pileup $c_pileup --c_bwa $c_bwa --c_bowtie $c_bowtie \
--s_name $sample_name --s_pileup $s_pileup --s_bwa $s_bwa --s_bowtie $s_bowtie --platform $platform \
--ordered_genes $ordered_genes --db_h $db_h --db_u $db_u --db_p $db_p --db_d $db_d --db_s $db_s --p 0

mysqladmin --socket=$INSTALL_PATH/mysql/thesock shutdown -u root

rm -rf *.pbs.*
rm -rf *.gz
rm -rf calibrate
rm -rf DBI
rm -rf getopt
rm -rf MASS 
rm -rf mysq*
rm -rf optparse
rm -rf plotrix
rm -rf RMySQL
rm -rf zoo
rm -rf *.sql
rm -rf test_cnv_*
rm -rf *~
rm -rf ordered_genes.txt
rm -rf CopyNumberDeletion.R
