#!/bin/bash                             
#PBS -l nodes=1:ppn=4,mem=15gb,walltime=2:00:00
#PBS -m abe
#PBS -M onson001@umn.edu

module load R/3.1.1

INSTALL_PATH=/home/msistaff/onson001/local_install/cnv
SCRIPT_PATH=/home/msistaff/onson001/Fairview/cnv/code/cnv-galaxy/myTools
MYSQL_LOAD_WAIT=120

cd $INSTALL_PATH

export PATH=$INSTALL_PATH/mysql-5.6.24-linux-glibc2.5-x86_64/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$INSTALL_PATH/mysql-5.6.24-linux-glibc2.5-x86_64/lib

# START MYSQL 
mysqld --innodb_buffer_pool_size=4G --basedir=$INSTALL_PATH/mysql --datadir=$INSTALL_PATH/mysql/data --log-error=$INSTALL_PATH/mysql/data/mysql.err --pid-file=$INSTALL_PATH/mysql/mysql.pid --socket=$INSTALL_PATH/mysql/thesock --port=3306 --lc-messages-dir=$INSTALL_PATH/mysql-5.6.24-linux-glibc2.5-x86_64/share/english &
sleep $MYSQL_LOAD_WAIT

wget https://s3.msi.umn.edu/CNVMySQL/CopyNumberDeletion.R
wget https://s3.msi.umn.edu/CNVMySQL/cnv_test_data.tar.gz

tar xzvf cnv_test_data.tar.gz

db_h="localhost"
db_u="root"
db_p="NULL"
db_d="cnv"
db_s="$INSTALL_PATH/mysql/thesock"

c_sample_name="07_2151";
c_pileup="test_cnv_07_2151_tso_pileup.txt"
c_bwa="test_cnv_07_2151_tso_bwa_pileup.txt"
c_bowtie="test_cnv_07_2151_tso_bowtie_pileup.txt"
sample_name="11_05910";
s_pileup="test_cnv_11_05910_tso_pileup.txt"
s_bwa="test_cnv_11_05910_tso_bwa_pileup.txt"
s_bowtie="test_cnv_11_05910_tso_bowtie_pileup.txt"
platform="TruSightOne";
ordered_genes="ordered_genes.txt"

Rscript $SCRIPT_PATH/runCNDtest.R  --c_name $c_sample_name --c_pileup $c_pileup --c_bwa $c_bwa --c_bowtie $c_bowtie \
--s_name $sample_name --s_pileup $s_pileup --s_bwa $s_bwa --s_bowtie $s_bowtie --platform $platform \
--ordered_genes $ordered_genes --db_h $db_h --db_u $db_u --db_p $db_p --db_d $db_d --db_s $db_s --p 0

mysqladmin --socket=$INSTALL_PATH/mysql/thesock shutdown -u root
